const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const progressKey='eap-progress-v2';const saved=JSON.parse(localStorage.getItem(progressKey)||'{"stars":0,"missions":{}}');
const state={stars:saved.stars||0,missions:saved.missions||{},mission:null,round:0,roundStars:0,selectedPet:null,music:false};state.stars=Object.keys(state.missions).length*3;
const games={
 pronoun:{title:'Pronoun Quest',steps:[['👧🏽','Maya is reading a map. Which pronoun crosses her bridge?','She',['He','She','They']],['👦🏻 👦🏾','Leo and Sam are building a raft. Choose their team pronoun!','They',['We','They','He']],['🧒🏼','You are our brave explorer! Which word means the person we talk to?','You',['I','You','She']]]},
 dress:{title:'Dress the Character',steps:[['Luca','👦🏻','Luca is looking for ___ blue cap.','his','🧢',[['🧢','blue cap'],['👒','sun hat'],['👟','shoes'],['🎒','bag']]],['Ella','👧🏾','Ella has a new yellow bag. It is ___ bag.','her','🎒',[['🎒','yellow bag'],['🧢','cap'],['👟','shoes'],['🧥','coat']]],['the team','🧒🏻 🧒🏽','The team packed a tent. It is ___ tent.','their','⛺',[['⛺','tent'],['🎒','backpack'],['🧢','cap'],['👕','T-shirt']]]]},
 pet:{title:'Pet Match',steps:[['Match the pets with the owner who loves them!',[['🐶','Mia','👧🏻','her'],['🐱','Ben','👦🏾','his'],['🐰','the children','🧒🏼 🧒🏽','their']]]]} };
function save(){state.stars=Object.keys(state.missions).length*3;localStorage.setItem(progressKey,JSON.stringify({stars:state.stars,missions:state.missions}));updateProgress()}
function updateProgress(){const completed=Object.keys(state.missions).length;$('#totalStars').textContent=state.stars;$('#completed').textContent=`${completed} / 3`;const p=Math.round(completed/3*100);$('#progressFill').style.width=p+'%';$('#progressText').textContent=p+'%'}
function sound(kind='click'){if(!state.music&&kind==='music')return;try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value={click:450,good:760,bad:150,victory:620}[kind]||340;g.gain.setValueAtTime(.07,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.18);o.start();o.stop(c.currentTime+.2)}catch(e){}}
function speak(text){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-GB';u.rate=.9;const voice=speechSynthesis.getVoices().find(v=>v.lang==='en-GB');if(voice)u.voice=voice;speechSynthesis.speak(u)}
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1600)}
function dots(count=3){$('#dots').innerHTML=Array.from({length:count},(_,i)=>`<i class="${i<state.round?'done':''}"></i>`).join('')}
function openMission(id){sound();state.mission=id;state.round=0;state.roundStars=0;$('#homeScreen').classList.remove('active');$('#gameScreen').classList.add('active');$('#missionLabel').textContent=games[id].title.toUpperCase();renderGame()}
function renderGame(){const id=state.mission;$('#roundStars').textContent=state.roundStars;dots(id==='pet'?1:3);if(id==='pronoun')return renderPronoun();if(id==='dress')return renderDress();renderPets()}
function common(title,lead,content){$('#gameContent').innerHTML=`<section class="mission-stage"><button class="speaker" data-say="${lead}" aria-label="Read task aloud">🔊</button><h1>${title}</h1><p class="lead">${lead}</p>${content}</section>`;$('.speaker').onclick=e=>speak(e.currentTarget.dataset.say)}
function renderPronoun(){const [avatar,line,correct,answers]=games.pronoun.steps[state.round];common('Pronoun Quest',line,`<div class="quest-scene"><div class="character">${avatar}</div><div class="speech">“${line}”</div><div>🌉</div></div><div class="pronoun-lanes">${answers.map(a=>`<button class="answer" data-answer="${a}">${a}</button>`).join('')}</div>`);$$('.answer').forEach(b=>b.onclick=()=>answer(b,b.dataset.answer===correct))}
function renderDress(){const [name,avatar,line,correct,target,items]=games.dress.steps[state.round];common('Dress the Character',line,`<div class="dress-room"><div class="character-card"><div class="dress-avatar">${avatar}</div><b>${name}</b><p>${line.replace('___','<strong>___</strong>')}</p><div class="target">Needs: ${target}</div></div><div class="closet">${items.map(([icon,label])=>`<button class="clothing" data-word="${icon===target?correct:'no'}">${icon}<span>${label}</span></button>`).join('')}</div></div>`);$$('.clothing').forEach(b=>b.onclick=()=>answer(b,b.dataset.word===correct))}
function renderPets(){const pets=games.pet.steps[0][1];common('Pet Match',games.pet.steps[0][0],`<div class="pet-board">${pets.map((p,i)=>`<button class="pet" data-i="${i}">${p[0]}</button>`).join('')}</div><div class="pet-board">${pets.map((p,i)=>`<button class="owner" data-i="${i}"><span class="avatar">${p[2]}</span>${p[1]}'s pet<br><em>(${p[3]})</em></button>`).join('')}</div>`);$$('.pet').forEach(x=>x.onclick=()=>{state.selectedPet=x.dataset.i;$$('.pet').forEach(y=>y.classList.remove('selected'));x.classList.add('selected');sound()});$$('.owner').forEach(x=>x.onclick=()=>{if(state.selectedPet===null)return toast('Choose a pet first!');if(x.dataset.i===state.selectedPet){sound('good');x.classList.add('matched');$(`.pet[data-i="${state.selectedPet}"]`).classList.add('matched');state.selectedPet=null;if(!$('.pet:not(.matched)'))finish()}else{sound('bad');toast('Try another owner!')}})}
function answer(btn,ok){if(!ok){btn.classList.add('wrong');sound('bad');toast('Nearly! Listen and try again.');setTimeout(()=>btn.classList.remove('wrong'),500);return}sound('good');btn.classList.add('right');state.roundStars++;$('#roundStars').textContent=state.roundStars;setTimeout(()=>{state.round++;state.round<3?renderGame():finish()},550)}
function finish(){sound('victory');const id=state.mission;const isNew=!state.missions[id];state.missions[id]=true;if(isNew)state.stars+=3;save();common('Mission complete!','You did a brilliant job. Your Adventure Park map is shining brighter!',`<div class="result result-victory"><img class="victory-art" src="assets/victory-celebration.png" alt="Golden champion trophy with stars and confetti"><h2>Fantastic explorer!</h2><p>You earned 3 stars and learned new grammar magic.</p><button class="next-btn" data-home>Back to the map</button></div>`);$('[data-home]').onclick=goHome}
function goHome(){sound();$('#gameScreen').classList.remove('active');$('#homeScreen').classList.add('active');state.mission=null}
function help(){const id=state.mission;const title=id?games[id].title:'English Adventure Park';const text=id==='pronoun'?'Guide each explorer across the bridge by choosing the pronoun that talks about them. Three correct bridges win the mission.':id==='dress'?'Look at the character and their needed item. Tap the clothing that belongs in the sentence. Pack three items to win.':id==='pet'?'Tap a pet, then tap the owner. Match all three pets to win.':'Pick a mission card from the map. Tap the purple speaker whenever you want to hear instructions.';$('#modalContent').innerHTML=`<h2>How to play: ${title}</h2><p>${text}</p><ul><li>⭐ Every mission earns three stars.</li><li>🔊 Use the speaker to hear British English.</li><li>🏠 The map button always takes you home.</li></ul><button class="listen-btn" data-read="${text}">🔊 Listen to instructions</button>`;$('#modal').hidden=false;$('[data-read]').onclick=e=>speak(e.currentTarget.dataset.read)}
$$('[data-mission]').forEach(b=>b.onclick=()=>openMission(b.dataset.mission));$$('[data-home]').forEach(b=>b.onclick=goHome);$('#helpBtn').onclick=help;$('#closeModal').onclick=()=>$('#modal').hidden=true;$('#modal').onclick=e=>{if(e.target.id==='modal')e.currentTarget.hidden=true};$('#readBtn').onclick=()=>speak(state.mission?`You are playing ${games[state.mission].title}. Use the speaker button for this task.`:'Welcome to English Adventure Park. Choose your mission!');$('#musicBtn').onclick=()=>{state.music=!state.music;$('#musicBtn').textContent=state.music?'♫':'♩';toast(state.music?'Sounds on!':'Sounds off')};$$('[data-read]').forEach(b=>b.onclick=e=>speak(e.currentTarget.dataset.read));updateProgress();
$('#restartAdventure').onclick=()=>{document.getElementById('modalContent').innerHTML='<h2>Restart adventure?</h2><p>This will clear your stars, mission progress and certificate. You can play all three missions again from the beginning.</p><button class="next-btn" id="confirmRestart">Restart adventure</button>';document.getElementById('modal').hidden=false;document.getElementById('confirmRestart').onclick=()=>{state.missions={};state.stars=0;state.round=0;state.roundStars=0;localStorage.removeItem(progressKey);save();document.getElementById('modal').hidden=true;if(state.mission)goHome();toast('Adventure restarted!')}};
document.addEventListener('click',event=>{if(event.target.closest('[data-home]'))goHome()});
$('#readBtn').onclick=()=>{const bubble=$('.welcome');const greeting=bubble?bubble.textContent.replace(/\s+/g,' ').trim():'Hello, Explorer! Ready for today’s mission?';if(bubble){bubble.classList.remove('fox-speaking');requestAnimationFrame(()=>bubble.classList.add('fox-speaking'));setTimeout(()=>bubble.classList.remove('fox-speaking'),900)}speak(greeting)};
